name: Bug Report
labels: [bug]
body:
  - type: input
    id: version
    attributes:
      label: SDK Version
    validations:
      required: true
  - type: input
    id: dotnet_version
    attributes:
      label: .NET Version
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
